### ISSUE TITLE
Goblin traders mod doesn't work with this mod

### ISSUE THREAD

**Issue by Bartholemew-Dingleberry** [iMoonDay/TradeEnchantmentDisplay#2]
when i try to right click the goblin trader with this mod enabled i don't see a trading window, after turning off only this mod the goblin trader mod worked fine, just so you know.

**Comment by iMoonDay** [comment]
A fix is already planned. The issue is consistent with [issue #1](https://github.com/iMoonDay/TradeEnchantmentDisplay/issues/1) (though not in the same language)

**Comment by Bartholemew-Dingleberry** [comment]
ah ok, my bad
