### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by BelfaChan** [iMoonDay/TradeEnchantmentDisplay#3]
It's stuck when rendering to text，Is there a way to set the render distance or improve this?
![2024-10-19_23 07 46](https://github.com/user-attachments/assets/6072b949-aed9-4a5c-89bd-8e4404d0465d)
![2024-10-19_23 08 01](https://github.com/user-attachments/assets/15b36fe9-b17f-4607-9ff3-766a79e5aafc)

**Comment by iMoonDay** [comment]
你的截图似乎并没有在渲染我模组的内容啊，你截图里的渲染是Masa Gadget模组的吧？
如果要修改渲染距离，设置里面有。

**Comment by BelfaChan** [comment]
哦天哪，我后来发现了，MasaGadget找到关闭的选项了，打扰了😂

原本是因为想装一个附魔显示的模组，结果问问题找人找错了，报意思😂










加贺改二护
***@***.***






---Original---
From: ***@***.***&gt;
Date: Sat, Oct 19, 2024 23:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [iMoonDay/TradeEnchantmentDisplay] Stuck (Issue #3)




 
你的截图似乎并没有在渲染我模组的内容啊，你截图里的渲染是Masa Gadget模组的吧？
