### ISSUE TITLE
[1.19.2] Incompatible with CC:Tweaked

### ISSUE THREAD

**Issue by TheROFL98** [iMoonDay/TradeEnchantmentDisplay#4]
When interacting with a ComputerCraft Turtle (haven't tested regular computers but I imagine it will yield the same result) crashes my game.

Forge 43.4.4
CC:Tweaked 1.101.4
Trade Enchantment Display 1.1.3

[crash.txt](https://github.com/user-attachments/files/17955412/crash.txt)

**Comment by TheROFL98** [comment]
The bug doesn't seem to be reproducible with the latest version of the mods involved in 1.20.1, however downgrading CC:Tweaked to 1.105.1 seems to trigger the bug. Currently investigating further

**Comment by iMoonDay** [comment]
My mod tries to determine whether it is tradeable by accessing the block's menu, but ComputerCraft Turtle does not allow menus to be called on the client side, so it throws an exception

**Comment by TheROFL98** [comment]
I've determined that CC:Tweaked may have inadvertently fixed the issue with version 1.110.0, as testing that version against your mod doesn't seem to reproduce the bug.

**Comment by iMoonDay** [comment]
So do I need to make a fix for version 1.19.2?

**Comment by TheROFL98** [comment]
If that's possible, yes.

**Comment by iMoonDay** [comment]
It's easy, but it takes a while to upload

**Comment by TheROFL98** [comment]
That's completely fine! I can wait :)

**Comment by iMoonDay** [comment]
It should be fixed, but I haven't tested it. You can update and test it.
